[package]
name = "pigeon-server"
version = "0.1.0"
edition = "2024"

[dependencies]
pigeon-core = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
